### ISSUE TITLE
Error when using lambda destination: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by trietlam** [newrelic/node-newrelic#2489]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We use the [serverless-newrelic-lambda-layers](https://www.npmjs.com/package/serverless-newrelic-lambda-layers) plugin for our lambdas, which pulls the latest newrelic layer. We have experienced an issue whereby the newrelic agent mistakenly identifies the event as an api gateway proxy event when the [destination lambda](https://docs.aws.amazon.com/lambda/latest/dg/invocation-async-retain-records.html#invocation-async-destinations) is invoked, then tries to retrieve `pathname` property from a non-existent request url. This is preventing the lambda from running.

## Expected Behavior
The lambda should be executed successfully 

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

this is the error log

```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'pathname')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'pathname')",
        "    at Object.scrub (/opt/nodejs/node_modules/newrelic/lib/util/urltils.js:94:27)",
        "    at setWebRequest (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:328:29)",
        "    at Runtime.wrappedHandler (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:153:9)",
        "    at runInContextCb (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1188:22)",
        "    at AsyncLocalStorage.run (node:async_hooks:338:14)",
        "    at AsyncLocalContextManager.runInContext (/opt/nodejs/node_modules/newrelic/lib/context-manager/async-local-context-manager.js:65:36)",
        "    at TransactionShim.applySegment (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1178:25)",
        "    at Runtime.transactionWrapper (/opt/nodejs/node_modules/newrelic/lib/shim/transaction-shim.js:414:17)",
        "    at Runtime.patchHandlerSync [as handler] (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:140:25)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    ]
}
```

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

This can be replicated by using two lambdas.

One lambda deployed as a destination lambda.
The second lambda, performing any given operation, and configured to invoke the destination lambda on success or failure
After successfully executing the normal lambda operation the destination lambda will not be invoked and the logs will contain the information as per the description re: the undefined object when trying to get the `pathname` property.

This is the serverless.yml config snippet for reference
```
functions: 
 destination-lambda:
    handler: 'src/destination-lambda/index.handler'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'lambda:InvokeFunction'
        Resource: 'arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-main-lambda'

  main-lambda:
    handler: 'src/main-lambda/index.handler'
    destinations:
      onFailure: destination-lambda
      onSuccess: destination-lambda
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'lambda:InvokeFunction'
        Resource: 'arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-destination-lambda'
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: 18

## Additional context

I believe it has same root cause as https://github.com/newrelic/node-newrelic/issues/2291, where the logic to [determine if the event is a proxy event](https://github.com/newrelic/node-newrelic/blob/c0a5e646773c365897a908daf034881703dbd1df/lib/serverless/api-gateway.js#L113) only check for `version` property.
This is problematic because other events can also have `"version": "1.0"` or `"version": "2.0"`. In this case, the lambda destination [invocation event ](https://docs.aws.amazon.com/lambda/latest/dg/invocation-async-retain-records.html#invocation-async-destinations) has `"version": "1.0"`

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
