### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'opaque')

### ISSUE THREAD

**Issue by mlee-ag** [newrelic/node-newrelic#2894]
## Description

Getting the following which causing the pod to restart

```
/newrelic-instrumentation/node_modules/newrelic/lib/shim/shim.js:702
      parent.opaque ||
             ^

TypeError: Cannot read properties of null (reading 'opaque')
    at wrapper (/newrelic-instrumentation/node_modules/newrelic/lib/shim/shim.js:702:14)
    at ExceptionHandler._uncaughtException (/app/node_modules/winston/lib/winston/exception-handler.js:225:17)
    at process.emit (node:events:529:35)
    at process.wrappedEmit [as emit] (/newrelic-instrumentation/node_modules/newrelic/lib/instrumentation/core/globals.js:51:23)
    at process.<anonymous> (node:internal/process/execution:158:25)
    at process.wrappedFatalException [as _fatalException] (/newrelic-instrumentation/node_modules/newrelic/lib/instrumentation/core/globals.js:32:23)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.18.1
```

## Expected Behavior
No TypeError to be thrown

## Steps to Reproduce
We have multiple nodejs micro services running on Kubernetes, and APM is done using
```
apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-instrumentation
  namespace: newrelic
spec:
  agent:
    # Values supported: dotnet, java, nodejs, python, ruby, php
    language: nodejs

    # Values supported: newrelic-java-init:latest, newrelic-dotnet-init:latest, newrelic-node-init:latest, newrelic-python-init:latest, newrelic-ruby-init:latest, newrelic-php-init:latest, newrelic-php-init:musl
    image: newrelic/newrelic-node-init:12.11.1.0-nodejs18x
```

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
Node.js v18.18.1
newrelic/newrelic-node-init:12.11.1.0-nodejs18x
